print("Welcome to the tip calculator")
bill = float(input("What was the total bill? $"))
tip = float(input("How much tip would you like to give? 10, 12, or 15? "))
peoples = int(input("How many people to split the bill? "))
pay = round((bill - tip) / peoples)
print(f"Each person should pay: ${pay:.2f}")
